age = int(input(f"What is your age? "))
print(f"On your next birthday, you will be {age + 1}.")
print()
carton = int(input(f"How many egg cartons do you have? "))
print(f"You have {carton * 12} eggs. ")
print()
cookie = int(input(f"How many cookies do you have? "))
people = int(input(f"How many people are there? "))
print(f"Each person may have {cookie / people} cookies. ")